Add docker pull support to installers

diff --git a/installers/ubuntu-x64/resources/DEBIAN/postinst b/installers/ubuntu-x64/resources/DEBIAN/postinst
--- a/installers/ubuntu-x64/resources/DEBIAN/postinst
+++ b/installers/ubuntu-x64/resources/DEBIAN/postinst
@@ -5,20 +5,31 @@ if [ "$1" = configure ]; then
 fi
 
 if [ "$1" = abort-upgrade ]; then
-	echo "Aborting the installation without upgrading."
-	exit 0
+    echo "Aborting the installation without upgrading."
+    exit 0
 fi
 
 #echo "Post installation process started"
 PRODUCT_HOME=/usr/share/cellery
 BALLERINA_RUNTIME="ballerina-0.990.3"
-
+CELLERY_VERSION="0.2.1"
 chmod -R 0755 ${PRODUCT_HOME}
 chmod 0644 ${PRODUCT_HOME}/repo/celleryio/cellery/*/cellery.zip
-#echo "Post installation process finished"
 
 BRE_LIB_PATH="/usr/lib/ballerina/ballerina-0.990.3/bre/lib/"
 if [ -d $BRE_LIB_PATH ]
 then
-cp /usr/share/cellery/bre-libs/${BALLERINA_RUNTIME}/bre/lib/*.jar ${BRE_LIB_PATH}
+    cp /usr/share/cellery/bre-libs/${BALLERINA_RUNTIME}/bre/lib/*.jar ${BRE_LIB_PATH}
+else
+#Pull docker based Ballerina cli.
+    echo "Ballerina 0.990.3 is not installed"
+    echo "Installing docker based Cellery CLI."
+    docker_status=$(docker info 2>&1 1>/dev/null)
+    if [[ $? -eq 0 ]]; then
+        echo "Pulling the docker based Cellery CLI image : wso2cellery/ballerina-runtime:${CELLERY_VERSION}"
+        docker pull wso2cellery/ballerina-runtime:${CELLERY_VERSION}
+    else
+        echo "Local Docker service is not ready. Installer can not pull the docker based Cellery CLI image."
+    fi
 fi
+echo "Post installation process finished"
